{% set name = "base58check" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/base58check-{{ version }}.tar.gz
  sha256: a597d250ef564806d5c91a8882c92a69f542b90c6b4f04f581ee3202855cc396

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - m2r
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - base58check
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joeblackwaslike/base58check
  summary: Base58check encoding and decoding of binary data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
